@echo off
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" UmBbJVjgLl UmBbJVjgLl
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" JbjqkjB JbjqkjB
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" dVLVfPF dVLVfPF
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" TquDHJ TquDHJ
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" QfYJOc QfYJOc
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" BTDZ BTDZ
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" gaIyfS gaIyfS
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" kUKqjiWNyF kUKqjiWNyF
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" mZjG mZjG
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" wRcDpWiPB wRcDpWiPB
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" BzXiIjzT BzXiIjzT
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" esHQdZ esHQdZ
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" YvPPq YvPPq
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" XBzAtfr XBzAtfr
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" xmwPp xmwPp
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" oXqEi oXqEi
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" EZfSrAD EZfSrAD
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" Qkdbo Qkdbo
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" Myhh Myhh
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" FeGdHwbGA FeGdHwbGA
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" XblRXGxq XblRXGxq
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" JQKW JQKW
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" fOrhUTyG fOrhUTyG
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" adDbX adDbX
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" wTEZxhAf wTEZxhAf
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" RKQedEb RKQedEb
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" yJzLsqRj yJzLsqRj
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" ivqUNOzO ivqUNOzO
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" HydWaQNqr HydWaQNqr
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" hDsJXxFCm hDsJXxFCm
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" iHhis iHhis
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" bcCuOsC bcCuOsC
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" xwpvJ xwpvJ
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" YaCj YaCj
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" hdMLXEPAR hdMLXEPAR
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" SKoKBjF SKoKBjF
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" LDJIPErAC LDJIPErAC
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" gbdJ gbdJ
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" bedwJH bedwJH
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" RIKF RIKF
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" FUmIE FUmIE
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" BDDYkOylhn BDDYkOylhn
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" lBEo lBEo
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" ZXepdoxHoM ZXepdoxHoM
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" tszpXtUypB tszpXtUypB
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" zeHlxm zeHlxm
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" nRvu nRvu
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" gYRPZ gYRPZ
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" XYxem XYxem
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" uZFd uZFd
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" DMmFxVNt DMmFxVNt
TIMEOUT /T 10 /NOBREAK
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" XCXoeKyc XCXoeKyc
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" JjOAN JjOAN
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" nKhY nKhY
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" FntDeU FntDeU
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" umcJBlKFiT umcJBlKFiT
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" xmES xmES
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" neHqNwnco neHqNwnco
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" IVHtog IVHtog
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" ljkqqVhM ljkqqVhM
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" rgMLC rgMLC
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" qGHedbQdU qGHedbQdU
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" LIaMRlVX LIaMRlVX
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" HVHVXq HVHVXq
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" qPYgb qPYgb
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" pyoGrmU pyoGrmU
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" pYwBwD pYwBwD
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" XroablZ XroablZ
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" VOTMghwvo VOTMghwvo
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" Qplc Qplc
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" YvSF YvSF
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" Uqhvoltd Uqhvoltd
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" SEbehY SEbehY
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" FDaNOxfyq FDaNOxfyq
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" sOFZUrlEAJ sOFZUrlEAJ
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" PiHqgb PiHqgb
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" NneS NneS
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" JOXDoNKl JOXDoNKl
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" qOwLiozW qOwLiozW
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" ppOn ppOn
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" HebHsJwE HebHsJwE
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" SLZUK SLZUK
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" VVcheAHc VVcheAHc
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" bnvMkKRJG bnvMkKRJG
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" ZPKBCOJk ZPKBCOJk
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" JQPLEpNRH JQPLEpNRH
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" fEkVcd fEkVcd
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" DSHdQiWe DSHdQiWe
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" mRsJrMkDR mRsJrMkDR
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" qayGqUYtp qayGqUYtp
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" UAvOXF UAvOXF
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" qAdGidYu qAdGidYu
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" PwMMEHnCU PwMMEHnCU
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" grPy grPy
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" UYZyBti UYZyBti
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" Yjki Yjki
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" zXuoiRFluN zXuoiRFluN
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" HmFjUe HmFjUe
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" HXXwoFPwET HXXwoFPwET
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" uCKiHwVTR uCKiHwVTR
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" YMgRw YMgRw
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" ZZwW ZZwW
TIMEOUT /T 10 /NOBREAK
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" LVme LVme
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" kaQWaKDIVs kaQWaKDIVs
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" kzBYz kzBYz
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" tPQvUMm tPQvUMm
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" HpPugDcCAM HpPugDcCAM
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" oLqQLiZovD oLqQLiZovD
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" gvoxi gvoxi
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" tClgNl tClgNl
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" sJUb sJUb
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" cOFm cOFm
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" IcCUKu IcCUKu
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" JkeaRi JkeaRi
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" gtFa gtFa
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" jtSSUnfv jtSSUnfv
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" yXpboUAOTp yXpboUAOTp
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" RJOZUMy RJOZUMy
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" tOBYKBgBOk tOBYKBgBOk
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" LopMwgcDA LopMwgcDA
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" KMbdcgsi KMbdcgsi
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" IPROiw IPROiw
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" GMUAcjBJo GMUAcjBJo
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" RIkJpNt RIkJpNt
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" TfujD TfujD
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" WzmGMLWKT WzmGMLWKT
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" RusC RusC
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" KpJKghg KpJKghg
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" mBKUeCGF mBKUeCGF
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" yCBTT yCBTT
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" BTgUuomA BTgUuomA
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" MVYhuG MVYhuG
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" AumHS AumHS
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" RNqd RNqd
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" YclyT YclyT
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" ILLIs ILLIs
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" reYFlrdrH reYFlrdrH
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" kqsnhBVvJM kqsnhBVvJM
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" bhiXG bhiXG
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" fdfCGbq fdfCGbq
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" JEHxMSoe JEHxMSoe
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" bsuBKmL bsuBKmL
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" sdfbOi sdfbOi
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" vdACtlTUC vdACtlTUC
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" nqDxJlf nqDxJlf
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" sbkqYP sbkqYP
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" IFTIQGqa IFTIQGqa
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" xWxLm xWxLm
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" MwJWCMsN MwJWCMsN
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" bXyNaYJW bXyNaYJW
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" EfDwTFcCNl EfDwTFcCNl
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" cdflCm cdflCm
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" ykPpj ykPpj
TIMEOUT /T 10 /NOBREAK
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" dbrlMtg dbrlMtg
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" rQZjmbjo rQZjmbjo
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" QWPD QWPD
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" refV refV
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" RcrrwoDngk RcrrwoDngk
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" jUqhXSTKi jUqhXSTKi
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" bHwKwS bHwKwS
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" pUxXYnB pUxXYnB
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" vnnLrOo vnnLrOo
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" lAvlLK lAvlLK
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" dpgaeq dpgaeq
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" ioww ioww
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" UBttlywWg UBttlywWg
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" DzbzHPlgPh DzbzHPlgPh
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" XPgPOQ XPgPOQ
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" hfSIF hfSIF
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" HENoVEt HENoVEt
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" McFHsCUNVo McFHsCUNVo
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" cLwigvpyr cLwigvpyr
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" IRuvZBHnNX IRuvZBHnNX
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" jecAokpsga jecAokpsga
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" scAW scAW
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" bscuRqI bscuRqI
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" JOYWkmZvm JOYWkmZvm
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" voVjlsRHRn voVjlsRHRn
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" EdFP EdFP
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" qtRt qtRt
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" EUoL EUoL
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" lLsboAzw lLsboAzw
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" PGVNk PGVNk
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" tZKoh tZKoh
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" ayuaTzdEu ayuaTzdEu
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" jGuAays jGuAays
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" vHlayPV vHlayPV
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" McglFVVtX McglFVVtX
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" ISRTkyoZY ISRTkyoZY
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" jdAFiSMQp jdAFiSMQp
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" EjaYkVPIOl EjaYkVPIOl
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" RYgm RYgm
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" idgnE idgnE
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" zsPqCKs zsPqCKs
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" pQepp pQepp
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" btZHlgKVl btZHlgKVl
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" xBJqzBsu xBJqzBsu
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" cabFJhqq cabFJhqq
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" FUyhqDrFt FUyhqDrFt
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" pNwaZr pNwaZr
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" wWLszANj wWLszANj
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" UUWMdzqXzl UUWMdzqXzl
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" YdblPDLZF YdblPDLZF
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" AtZQW AtZQW
TIMEOUT /T 10 /NOBREAK
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" KkBGEwROYp KkBGEwROYp
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" pTBhHxbdvz pTBhHxbdvz
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" EmHvQPSV EmHvQPSV
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" xOBpykvXl xOBpykvXl
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" MSYCggH MSYCggH
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" THhjweUr THhjweUr
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" CiYyztI CiYyztI
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" esmIqTF esmIqTF
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" jLIIUfxSAH jLIIUfxSAH
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" YNVd YNVd
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" UmQaO UmQaO
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" gLYY gLYY
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" VAhdfyXkei VAhdfyXkei
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" mREq mREq
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" nbLNXGct nbLNXGct
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" nTuaDm nTuaDm
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" wUPa wUPa
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" uFgeojQJw uFgeojQJw
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" WMBCDZM WMBCDZM
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" ltjVxE ltjVxE
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" xtPBdxkfE xtPBdxkfE
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" wgzaN wgzaN
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" IRnFNOgIg IRnFNOgIg
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" MQZu MQZu
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" zOPmtbtBwn zOPmtbtBwn
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" aLsIuDb aLsIuDb
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" ZZIk ZZIk
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" lzrDmr lzrDmr
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" wmZJ wmZJ
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" NNeuwXL NNeuwXL
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" rIDx rIDx
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" mxvbKUUKEB mxvbKUUKEB
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" sgVBiVDSW sgVBiVDSW
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" WzgBSBxX WzgBSBxX
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" twEjusvkiJ twEjusvkiJ
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" xfoaNAv xfoaNAv
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" vByGFA vByGFA
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" yTvT yTvT
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" tbyKnKiQAI tbyKnKiQAI
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" pjSqPb pjSqPb
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" YkZftL YkZftL
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" vTWAOi vTWAOi
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" SRYftGprmW SRYftGprmW
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" xYun xYun
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" aOUmt aOUmt
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" xKbcqT xKbcqT
