@echo off
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" UmBbJVjgLl UmBbJVjgLl
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" JbjqkjB JbjqkjB
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" dVLVfPF dVLVfPF
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" TquDHJ TquDHJ
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" QfYJOc QfYJOc
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" BTDZ BTDZ
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" gaIyfS gaIyfS
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" kUKqjiWNyF kUKqjiWNyF
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" mZjG mZjG
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" wRcDpWiPB wRcDpWiPB
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" BzXiIjzT BzXiIjzT
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" esHQdZ esHQdZ
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" YvPPq YvPPq
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" XBzAtfr XBzAtfr
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" xmwPp xmwPp
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" oXqEi oXqEi
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" EZfSrAD EZfSrAD
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" Qkdbo Qkdbo
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" Myhh Myhh
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" FeGdHwbGA FeGdHwbGA
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" XblRXGxq XblRXGxq
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" JQKW JQKW
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" fOrhUTyG fOrhUTyG
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" adDbX adDbX
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" wTEZxhAf wTEZxhAf
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" RKQedEb RKQedEb
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" yJzLsqRj yJzLsqRj
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" ivqUNOzO ivqUNOzO
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" HydWaQNqr HydWaQNqr
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" hDsJXxFCm hDsJXxFCm
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" iHhis iHhis
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" bcCuOsC bcCuOsC
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" xwpvJ xwpvJ
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" YaCj YaCj
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" hdMLXEPAR hdMLXEPAR
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" SKoKBjF SKoKBjF
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" LDJIPErAC LDJIPErAC
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" gbdJ gbdJ
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" bedwJH bedwJH
start "" /B "C:\Users\dmitr\PycharmProjects\DAOEM_v1\venv\Scripts\python.exe" "C:\Users\dmitr\PycharmProjects\DAOEM_v1\client.py" RIKF RIKF